<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, jQuery Image Slider Example, jQuery Slider 2011" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/13_low.jpg" alt="1-3_low" title="1-3_low" id="wows1_0"/></li>
<li><img src="data1/images/2.jpg" alt="2" title="2" id="wows1_1"/></li>
<li><img src="data1/images/20160402232423.jpg" alt="20160402232423" title="20160402232423" id="wows1_2"/></li>
<li><img src="data1/images/thumb4.jpg" alt="thumb4" title="thumb4" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="1-3_low"><img src="data1/tooltips/13_low.jpg" alt="1-3_low"/>1</a>
<a href="#" title="2"><img src="data1/tooltips/2.jpg" alt="2"/>2</a>
<a href="#" title="20160402232423"><img src="data1/tooltips/20160402232423.jpg" alt="20160402232423"/>3</a>
<a href="#" title="thumb4"><img src="data1/tooltips/thumb4.jpg" alt="thumb4"/>4</a>
</div></div>
<a class="wsl" href="http://wowslider.com">jQuery Background Slider by WOWSlider.com v2.7.1</a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>